config/routes.rb
JapanpageShare::Application.routes.draw do
  post "friendship/create"
  get "friendship/destroy"
  get "friendship/confirm"

  devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_up => "register", :sign_out => "logout"}
  root :to => "home#index"
  resources :people, :only => 'index'

  resources :user, :path => "", :controller => 'user' do
    resources :post, :only => [:destroy, :create]
    resources :friendship, :only => 'index'
    resources :photo, :only => [:index, :show, :create, :destroy]
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = current_user
    @users = User.all
    @friendships = User.friendships_hash(@users,@user.friendships_array)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

end

app/views/people/_partial.html.erb
<div>
    <h1>Hello i am <%=a %></h1>
</div>

app/views/people/index.html.erb
<div class="container-narrow">
  <h1>
    People
  </h1>
  <br/>

  <div class="span8">
    <table class="condensed-table">
      <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <th class="media-grid">
              <%= link_to image_tag(user.avatar.url(:post)), user_path(user) %>
            </th>
            <th><%= link_to user.full_name, user_path(:id => user.id) %></th>
            <% friendship = @friendships[user.id] %>
            <th>
              <% unless user == current_user %>
                  <% if friendship %>
                      <% unless friendship.is_confirmed.nil? %>
                          Is your Friend <%= link_to "Remove", friendship_destroy_path(:id => friendship.id) %>
                      <% else %>
                          <% if current_user.id == friendship.friend_id %>
                              <%= link_to "Accept", friendship_confirm_path(:id => friendship.id) %>
                              <%= link_to "Reject", friendship_destroy_path(:id => friendship.id) %>
                          <% else %>
                              You've sent request to <%= user.name %>
                          <% end %>
                      <% end %>
                  <% else %>
                      <%= link_to "Add Friend", friendship_create_path(:friend_id => user), :method => :post %>
                  <% end %>
              <% end %>
            </th>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>