config/routes.rb
JapanpageShare::Application.routes.draw do
  post "friendship/create"
  get "friendship/destroy"
  get "friendship/confirm"

  devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_up => "register", :sign_out => "logout"}
  root :to => "home#index"
  resources :people, :only => 'index'

  resources :user, :path => "", :controller => 'user' do
    resources :post, :only => [:destroy, :create]
    resources :friendship, :only => 'index'
    resources :photo, :only => [:index, :show, :create, :destroy]
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, :styles => { :small => "145x145#", :normal => "640x480>"},
                    :url => "/images/albums/users/:id/:basename_:style.:extension",
                    :path => ":rails_root/public/images/albums/users/:id/:basename_:style.:extension"

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 2.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  before_filter :load_user
  def index
    @photos = @user.photos.paginate(:page => params[:page], :per_page => 12)
  end

  def show
  end

  def create
    @photo = Photo.new(params[:photo])
    @photo.user_id = params[:user_id]
    if @photo.save
      flash[:notice] = "Photo Added"
      redirect_to user_photo_index_path current_user
    else
      flash[:error] = "Error"
      redirect_to user_photo_index_path current_user
    end
  end

  def destroy
    Photo.find_by_id(params[:id]).destroy
    redirect_to user_photo_index_path current_user
  end

private
  def load_user
    @user = User.find_by_id(params[:id] || current_user.id)
  end
end

app/views/photo/index.html.erb
<div class="span13">
  <br />
  <% if @user == current_user %>
      <%= form_for :photo, :url => user_photo_index_path(:user_id => @user.id), :method => :post, :html => {:multipart => true} do |f| %>
          <%= f.file_field :image %>
          <%= f.submit "Add", :class => "btn primary" %>
          <%= %>
      <% end %>
  <% end %>
  <div class="span offset1"><h6>Photos: <%=@photos.count%></h6></div>
  <div class="row well-photo gallery">
    <% @photos.each do |photo| %>
        <div class="well-photo span3">
          <%= link_to(image_tag(photo.image.url(:small)), photo.image.url(:normal), :class=>"image") %>
          <%= link_to 'x', user_photo_path(:user_id => @user.id, :id => photo.id), :method => :delete, :class => "close" %>
        </div>
    <% end %>
  </div>
  <div class="span3"> <%= will_paginate @photos if @photos.respond_to? :total_pages %></div>
</div>