config/routes.rb
JapanpageShare::Application.routes.draw do
  post "friendship/create"
  get "friendship/destroy"
  get "friendship/confirm"

  devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_up => "register", :sign_out => "logout"}
  root :to => "home#index"
  resources :people, :only => 'index'

  resources :user, :path => "", :controller => 'user' do
    resources :post, :only => [:destroy, :create]
    resources :friendship, :only => 'index'
    resources :photo, :only => [:index, :show, :create, :destroy]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :friendships,
           :conditions => { :is_confirmed => true }

  has_many :friends,
           :through => :friendships

  has_many :inverse_friendships,
           :conditions => { :is_confirmed => true },
           :class_name => "Friendship",
           :foreign_key => :friend_id

  has_many :inverse_friends,
           :through => :inverse_friendships,
           :source => :user

  has_many :friendship_requests,
           :class_name => "Friendship",
           :foreign_key => "friend_id",
           :conditions => { :is_confirmed => nil }

  has_many :potential_friends,
           :through => :friendship_requests,
           :source => :user

  has_many :wanted_friendships, :class_name => "Friendship",
           :conditions => { :is_confirmed => nil }

  has_many :wanted_friends, :through => :wanted_friendships,
           :source => :friend

  has_many :photos

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :profile => "280x210#", :post => "90x90#" },
                    :url => "/images/users/:id/:basename_:style.:extension",
                    :path => ":rails_root/public/images/users/:id/:basename_:style.:extension",
                    :default_url => "/images/missing_:style.jpg"

  validates_presence_of :name, :surname
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :surname, :nickname, :birthday, :sex, :country, :city,
                  :phone, :skype, :university, :school, :interests, :address,
                  :email, :password, :password_confirmation, :remember_me, :friend, :friendship,
                  :inverse_friend, :inverse_friendship, :id, :status,
                  :avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at,
                  :image_file_name,:image_content_type,:image_file_size,:image_updated_at, :user_id, :name,:created_at,:updated_at


  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']

  def friendship(user)
    Friendship.find_by_user_id_and_friend_id(self.id, user.id) || Friendship.find_by_user_id_and_friend_id(user.id, self.id)
  end

  def friend?(user)
    Friendship.find_by_user_id_and_friend_id(self.id, user.id).nil? || Friendship.find_by_user_id_and_friend_id(user.id, self.id).nil?
  end



  def self.friendships_hash(users,friendships)
    result = nil
    if friendships.count != 0
      result = users.inject(Hash.new) { |hash,element|
        hash[element.id] = friendships.detect{|e| e.friend_id == element.id or e.user_id == element.id}
        hash
      }
    end
    result
  end

  def random_friends
    all_friends.shuffle.first(4)
  end

  def full_name
    "#{self.name} #{self.surname}"
  end

  def posts
    Post.find_user_posts(self)
  end

  def get_status(user)
    if status.nil? or status.empty?
      self.id != user.id ? "" : "Click here to change your status"
    else
      status
    end
  end

  def requests_num
    friendship_requests.count
  end

  def all_friends
    friends + inverse_friends
  end

  def all_friendships
    fr_indirect = inverse_friendships
    fr_indirect.each do |t|
      t.user_id, t.friend_id = t.friend_id, t.user_id
    end
    friendships + fr_indirect
  end

  def friendships_array
    Friendship.where("user_id = ? or friend_id = ?",id,id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_user
  def show
    @posts = @user.posts.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    redirect_to user_path(:id => params[:id]) if params[:id] != current_user.id.to_s
  end

  def update
    #binding.pry
    @user.update_attributes(params[:user])
    respond_to do |format|
      format.js do
        render :js => "alert(OK);"
      end
      format.html { redirect_to edit_user_path(@user.id)}
    end
  end

private
  def load_user
    @user = User.find_by_id(params[:id] || current_user.id)
  end
end

app/helpers/user_helper.rb
module UserHelper

  def user_info(user)
    {
      "Short info" => { "Birthday" => user.birthday,
                        "Interests" => user.interests},
      "Contacts"   => { "Country" => user.country,
                        "City" => user.city,
                        "Phone" => user.phone,
                        "Skype" => user.skype,
                        "Address" => user.address},
      "Education"  => { "School" => user.school,
                        "University" => user.university}
    }
  end

end

app/views/user/_edit_actions.erb
<div class="actions">
  <%= form.submit "Save Changes", :class => "btn primary"%>
</div>

app/views/user/_edit_select_and_textarea.erb
<div class="clearfix">
  <%= form.label params[0], params[0].to_s.camelize %>
    <div class="input">
      <%= form.text_area params[0],:rows => 5, :class => "span5" %>
    </div>
</div>
<div class="clearfix">
  <%= form.label params[1], params[1].to_s.camelize %>
    <div class="input">
      <%= form.date_select params[1], {},{ :class => "mini" } %>
    </div>
</div>
<div class="clearfix">
  <%= form.label params[2], params[2].to_s.camelize %>
  <div class="input">
    <%= form.select params[2], { "Male" => "true", "Female" => "false"},{},{:class => "small"}%>
  </div>
</div>

app/views/user/_edit_text_field.html.erb
<% params.each do |param| %>
  <div class="clearfix">
    <%= form.label param, param.to_s.camelize %>
    <div class="input">
      <%= form.text_field(param,:class => "span5")  %>
    </div>
  </div>
<% end %>

app/views/user/_show_info.erb
<div class="row">
  <% if value.present? %>
      <div class="span text"><%= name %></div>
      <span class="span-long"><%= value %></span>
  <% end %>
</div>

app/views/user/_show_links.erb
<% if user_signed_in? and user == current_user %>
    <div class="page-header-edit">
      <h6>
        <span class="page-header-text-color"><%= link_to "Edit page", edit_user_path %></span>
      </h6>
    </div>
<% else %>
    <% if friendship %>
        <% if friendship.is_confirmed != nil %>
            <div class="well-friends">
              <div class="row">
                <div class="span-small label notice"> Is your Friend</div>
                <span><%= link_to "Remove", friendship_destroy_path(:id => friendship.id), :class => "label important" %></span>
              </div>
            </div>
        <% else %>
            <% if current_user.id == friendship.friend_id %>
                <div class="well">
                  <div class="row">
                    <div class="span4 label notice"><%= user.name %> wants to be your friend</div>
                    <div class="span4 offset2">
                      <%= link_to "Accept", friendship_confirm_path(:id => friendship.id), :class => "btn primary small" %>
                      <%= link_to "Reject", friendship_destroy_path(:id => friendship.id), :class => "btn danger small" %>
                    </div>
                  </div>
                </div>
            <% else %>
                You've sent request to <%= user.name %>
            <% end %>
        <% end %>
    <% else %>
        <div class="well-friends">
          <div class="row">
            <div class="span-medium label notice"> Is Not Your Friend</div>
            <span><%= link_to "Add", friendship_create_path(:friend_id => @user.id), :class => "label important", :method => :post %></span>
          </div>
        </div>
    <% end %>
<% end %>
<div class="page-header-edit">
  <h6>
    <span class="page-header-text-color"><%= link_to "Photos", user_photo_index_path(:user_id => @user.id) %></span>
  </h6>
</div>

app/views/user/_show_status.erb
<% if @user == current_user %>
    <div class="status-container well">
      <span class="current-status"><%= @user.get_status(current_user) %></span>
      <%= form_tag user_path(@user.id), :remote => true, :class => 'status-editable-container', :style => "display:none" do %>
          <%= text_field_tag "user[status]", @user.get_status(current_user), :class => 'status-editable' %>
          <%= submit_tag "update", :class => "btn primary" %>
          <%= link_to "cancel", "", :class => "btn danger status-cancel-edit" %>
      <% end %>
    </div>
<% else %>
    <%= @user.get_status(current_user) %>
<% end %>

app/views/user/edit.html.erb
<div class="page-header">
  <h3>
     Here you can manage your Profile
  </h3>
</div>

<div class="span8">
  <ul class="tabs" data-tabs="tabs">
    <li class="active"> <a href="#photo">Photo</a> </li>
    <li> <a href="#main">Main</a></li>
    <li> <a href="#contacts">Contacts</a></li>
  </ul>
  <div class="pill-content">
    <div class="tab-content active" id="photo">
      <ul class="media-grid">
        <li>
          <%= link_to image_tag(current_user.avatar.url(:profile)), nil %>
        </li>
      </ul>
      <%= form_for current_user, :url => user_path(:id => current_user.id), :method => :put, :html => {:multipart => true} do |f| %>
          <%= f.file_field :avatar %>
          <%= render :partial => "edit_actions", :locals => {:form => f} %>
      <% end %>
    </div>
    <div class="tab-content" id="main">
      <%= form_for current_user,:url => user_path(:id => current_user.id), :method => :put, :html => {:multipart => true, :class => "edit-container"} do |f| %>
        <fieldset>
          <%= render :partial => "edit_text_field",:locals => { :form => f, :params => [:name, :surname, :nickname] } %>
          <%= render :partial => "edit_select_and_textarea",:locals => {:form => f,:params => [:interests,:birthday,:sex]} %>
        </fieldset>
        <%= render :partial => "edit_actions",:locals => {:form => f} %>
      <% end %>
    </div>
    <div class="tab-content" id="contacts">
      <%= form_for current_user,:url => user_path(:id => current_user.id), :method => :put, :html => {:multipart => true, :class => "edit-container"} do |f| %>
        <fieldset>
          <%= render :partial => "edit_text_field",:locals => {:form => f, :params => [:country, :city, :phone, :skype, :school, :university, :address ] } %>
        </fieldset>
        <%= render :partial => "edit_actions",:locals => {:form => f} %>
      <% end %>
    </div>

  </div>
</div>

app/views/user/show.html.erb
<%= content_for :js do %>
    <script type="text/javascript">
        var faye = new Faye.Client('<%=request.server_name%>:9292/faye');
        faye.subscribe("/messages/new/<%= @user.id %>", function(data) {
            eval(data);
        });
    </script>
<% end %>
<div class="container-main">
  <div class="page-header-main">
    <h3>
    <span class="page-header-text-color">
      <% if user_signed_in? and @user == current_user %>
        <%= current_user.full_name %> (This is You)
      <% else %>
        <%= @user.full_name %>
      <% end %>
    </span>
    </h3>
  </div>

  <div class="row">
    <div class="span5 links">
      <%= render :partial => "show_links", :locals => {:user => @user, :friendship => @user.friendship(current_user)} %>
      <div class="well-friends">
        <div class="page-header">
          <%= link_to "Friends   #{@user.all_friends.count}", user_friendship_index_path(:user_id => @user.id), :class => "span" %>
        </div>
        <% @user.random_friends.each do |friend| %>
            <div class="row">
              <div class="span2"><br/><%= link_to friend.full_name, user_path(:id => friend.id) %></div>
              <div class="span2">
                <ul class="media-grid">
                  <li><%= link_to image_tag(friend.avatar.url(:post)), user_path(friend.id) %></li>
                </ul>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <div class="span8 userinfo">
      <%= render :partial => "show_status" %>
      <div class="well">
        <% user_info(@user).each do |section, value| %>
            <br />
            <div class="page-header label notice"><%= section %></div>
            <% value.each do |name, value| %>
                <%= render :partial => "show_info", :locals => {:name => name, :value => value} %>
            <% end %>
        <% end %>
      </div>


      <div class="well">
        <div class="page-header-main">
          <h3>
            <span class="page-header-text-color">Wall</span>
          </h3>
        </div>
        <%= form_tag user_post_index_path(@user), :remote => true do %>
            <%= text_area_tag "post[message]", "",
                              :id => 'post_form', :rows => 4,
                              :class => 'span7',
                              :placeholder=> 'Write a message..'
            %>
            <%= submit_tag "Post", :class => 'btn primary' %>
        <% end %>
        <div id="wall_posts" class="content">
          <%= will_paginate @posts if @posts.respond_to? :total_pages %>
          <% @posts.each do |post| %>
              <%= render :partial => 'post/post', :locals => {:post => post} %>
          <% end %>
          <%= will_paginate @posts if @posts.respond_to? :total_pages %>
        </div>
      </div>
    </div>
  </div>
</div>